export const LOGIN_USER = 'LOGIN_USER';
export const GET_ALL_PEOPLE = 'GET_ALL_PEOPLE'
export const GET_ALL_PLANETS = 'GET_ALL_PLANETS'
export const UPDATE_SEARCH_COUNT = 'UPDATE_SEARCH_COUNT'
export const CLEAR_SEARCH_COUNT = 'CLEAR_SEARCH_COUNT'
export const GET_PEOPLE = 'GET_PEOPLE'
